run:
  timeout: 5m
  tests: false
linters:
   enable-all: true
   disable:
     - err113
     - goimports
     - cyclop
     - depguard
     - exhaustruct
     - forbidigo
     - forcetypeassert
     - gci
     - gochecknoglobals
     - gochecknoinits
     - godox
     - godot
     - gofumpt
     - gomnd
     - lll
     - musttag
     - nakedret
     - nlreturn
     - nolintlint
     - nonamedreturns
     - tagalign
     - tagliatelle
     - varnamelen
     - wrapcheck
     - goconst # not needed in our case
     - perfsprint # not needed in our case
linters-settings:
   funlen:
     ignore-comments: true
     lines: 80
   nestif:
     min-complexity: 5
