# See documentation at https://goreleaser.com
before:
  hooks:
    - go mod download
builds:
  - id: netways-support-collector
    binary: netways-support-collector
    env:
      - CGO_ENABLED=0
    goarch:
      - amd64
    goos:
      - linux
    ldflags:
      - >-
        -s -w -X main.version={{.Version}}
        -X main.commit={{.Commit}}
        -X main.date={{.CommitDate}}
release:
  github:
    owner: NETWAYS
    name: support-collector
archives:
  - format: binary
    name_template: >-
      {{ .ProjectName }}_{{ .Tag }}_
      {{- if eq .Os "linux" }}Linux{{ end }}
      {{- if eq .Os "windows" }}Windows{{ end }}
      {{- if eq .Os "darwin" }}Darwin{{ end }}
      {{- if eq .Arch "amd64" }}_x86_64{{ end }}
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: '{{ .Version }}-SNAPSHOT-{{.ShortCommit}}'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^goreleaser:'
